name: CI Preview

on:
  push:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run preview script
        run: chmod +x ./scripts/ci-preview.sh

      - name: Run preview script
        run: ./scripts/ci-preview.sh